name: .NET 7 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '7.0.x'
  PROJECT_PATH: 'API'
  SOLUTION_FILE: 'backend.sln'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: |
        cd ${{ env.PROJECT_PATH }}
        dotnet restore
    
    - name: Build
      run: |
        cd ${{ env.PROJECT_PATH }}
        dotnet build --configuration Release --no-restore
    
    - name: Publish
      run: |
        cd ${{ env.PROJECT_PATH }}
        dotnet publish --configuration Release --no-build --output ./publish
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: ${{ env.PROJECT_PATH }}/publish
